application: smartninja-students
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: /login2
  script: main.app
  secure: never

- url: /login2/thanks
  script: main.app
  secure: never

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest